# Generated by Django 6.0.6 on 2026-06-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('satellite', models.CharField(max_length=100)),
                ('band_type', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('original_image', models.ImageField(upload_to='uploads/')),
                ('enhanced_image', models.ImageField(blank=True, upload_to='enhanced/')),
                ('status', models.CharField(default='Completed', max_length=30)),
                ('accuracy', models.CharField(default='92%', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
